//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AdicionarAdministradorRequestDTO {
    Nome: string;
    email: string;
    password: string;
    confirmPassword: string;
}

export interface AdicionarUsuarioRequestDTO {
    Nome: string;
    email: string;
    password: string;
    confirmPassword: string;
}

export interface SolicitarAlteracaoSenhaRequestDTO {
    email: string;
}

export interface ResetarSenhaRequestDTO {
    email: string;
    password: string;
    confirmPassword: string;
}

export interface UserStatusRequestDTO {
    email: string;
}

export interface LoginRequestDTO {
    user: string;
    password: string;
    audience: string;
}

export interface RefreshTokenRequestDTO {
    token: string;
    refreshToken: string;
}

export interface AuthStatusResponseDTO {
    configured: boolean;
}

export interface UserStatusResponseDTO {
    ativo: boolean;
    refreshPasswordRequested: boolean;
    refreshPasswordApproved: boolean;
}

export interface TokenResponseDTO {
    accessToken: string;
    ehAdm: boolean;
    refreshToken: string;
    expiresIn: number;
    usuarioToken: UsuarioTokenResponseDTO;
}

export interface UsuarioTokenResponseDTO {
    id: string;
    Nome: string;
    claims: ClaimTokenResponseDTO[];
}

export interface ClaimTokenResponseDTO {
    value: string;
    type: string;
}