//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AdicionarTarefaRequest {
    idToDoList: string | undefined;
    index: number;
    descricao: string;
    status: number;
    nome: string;
    dataInicio: Date;
    dataFim: Date;
}

export interface AtualizarTarefaRequest {
    id: string;
    idToDoList: string | undefined;
    index: number;
    descricao: string;
    status: number;
    nome: string;
    dataInicio: Date;
    dataFim: Date;
}

export interface AtualizarStatusTarefaRequest {
    id: string;
    status: number;
}

export interface TarefaDTO {
    id: string;
    idToDoList: string | undefined;
    idUsuario: string;
    nomeUsuario: string;
    nome: string;
    status: number;
    descricao: string;
    index: number;
    dataInicio: Date;
    dataFim: Date;
    dataCriacao: Date;
    dataAtualizacao: Date;
    toDoList: ListaDTO | undefined;
}

export interface AdicionarListaRequest {
    nome: string;
    tarefas: AdicionarTarefaRequest[] | undefined;
}

export interface AtualizarListaRequest {
    id: string;
    nome: string;
}

export interface ListaDTO {
    id: string;
    idUsuario: string;
    nomeUsuario: string;
    nome: string;
    index: number;
    dataCriacao: Date;
    dataAtualizacao: Date;
}