//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AtualizarDadosDeUsuarioRequestDTO {
    Nome: string;
    email: string;
    password: string;
    confirmPassword: string;
}

export interface AtualizarUsuarioRequestDTO {
    idUsuario: string;
    nome: string;
}

export interface AdicionarPerfilDeUsuarioRequestDTO {
    idPerfil: string;
}

export interface AdicionarPermissaoUsuarioRequestDTO {
    identificadorPermissao: string;
}

export interface UsuarioResponseDTO {
    id: string;
    nome: string;
    email: string;
    ativo: boolean;
    atualizacaoSenhaRequisitada: boolean;
    atualizacaoSenhaAprovada: boolean;
}

export interface PerfilDeUsuarioResponseDTO {
    id: string;
    nome: string;

    [key: string]: any;
}